# Generated by Django 3.0.5 on 2024-05-04 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalsapp', '0002_contactmessage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doctor',
            options={},
        ),
    ]
